[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#080808"
textColor = "#ffffff"
primaryColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
