[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
backgroundColor = "#F7F5EF"
secondaryBackgroundColor = "#FFFEFA"
textColor = "#1F2933"
primaryColor = "#92A9E1"
font = "sans serif"

[browser]
gatherUsageStats = false
